apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: nginx
  if !watchSync && !watchHealth && !watchOperations && !watchSuspended { 
    watchSync = true 
    watchHealth = true 
    watchOperations = true 
    watchSuspended = false 
 } 
